export const enrichmentOutput = {
    AUS: {
        aus_regional_geocodes: {
            "latitude": "Latitude",
            "longitude": "Longitude",
            "match_level": "Match Level",
            "sa1": "Sa1",
            "meshblock": "Meshblock",
            "lga_code": "Lga Code",
            "lga_name": "Lga Name",
            "street_pid": "Street Pid",
            "locality_pid": "Locality Pid",
            "geocode_level_code": "Geocode Level Code",
            "geocode_level_description": "Geocode Level Description",
            "geocode_type_code": "Geocode Type Code",
            "geocode_type_description": "Geocode Type Description",
            "highest_level_longitude": "Highest Level Longitude",
            "highest_level_latitude": "Highest Level Latitude",
            "highest_level_elevation": "Highest Level Elevation",
            "highest_level_planimetric_accuracy": "Highest Level Plamimetric Accuracy",
            "highest_level_boundary_extent": "Highest Level Boundary Extent",
            "highest_level_geocode_reliability_code": "Highest Level Geocode Reliability Code",
            "highest_level_geocode_reliability_description": "Highest Level Geocode Reliability Description",
            "confidence_level_code": "Confidence Level Code",
            "confidence_level_description": "Confidence Level Description",
            "2021_meshblock_id": "2021 Meshblock Id",
            "2021_meshblock_code": "2021 Meshblock Code",
            "2021_meshblock_match_code": "2021 Meshblock Match Code",
            "2021_meshblock_match_description": "2021 Meshblock Match Description",
            "2016_meshblock_id": "2016 Meshblock Id",
            "2016_meshblock_code": "2016 Meshblock Code",
            "2016_meshblock_match_code": "2016 Meshblock Match Code",
            "2016_meshblock_match_description": "2016 Meshblock Match Description",
            "address_type_code": "Address Type Code",
            "primary_address_pid": "Primary Address Pid",
            "address_join_type": "Address Join Type",
            "collector_district_id": "Collector District Id",
            "collector_district_code": "Collector District Code",
            "commonwealth_electoral_boundary_id": "Commonwealth Electoral Boundary Id",
            "commonwealth_electoral_boundary_name": "Commonwealth Electoral Boundary Name",
            "statistical_local_area_id": "Statistical Local Area Id",
            "statistical_local_area_code": "Statistical Local Area Code",
            "statistical_local_area_name": "Statistical Local Area Name",
            "state_electoral_boundary_id": "State Electoral Boundary Id",
            "state_electoral_boundary_name": "State Electoral Boundary Name",
            "state_electoral_effective_start": "State Electoral Effective Start",
            "state_electoral_effective_end": "State Electoral Effective End",
            "state_electoral_new_pid": "State Electoral New Pid",
            "state_electoral_new_name": "State Electoral New Name",
            "state_electoral_new_effective_start": "State Electoral New Effective Start",
            "state_electoral_new_effective_end": "State Electoral New Effective End",
            "address_level_longitude": "Address Level Longitude",
            "address_level_latitude": "Address Level Latitude",
            "address_level_elevation": "Address Level Elevation",
            "address_level_planimetric_accuracy": "Address Level Planimetric Accuracy",
            "address_level_boundary_extent": "Address Level LatitudeBoundary Extent",
            "address_level_geocode_reliability_code": "Address Level Geocode Reliability Code",
            "address_level_geocode_reliability_description": "Address Level Geocode Reliability Description",
            "street_level_longitude": "Street Level Longitude",
            "street_level_latitude": "Street Level Latitude",
            "street_level_planimetric_accuracy": "",
            "street_level_boundary_extent": "Street Level Boundary Extent",
            "street_level_geocode_reliability_code": "Street Level Geocode Reliability Code",
            "street_level_geocode_reliability_description": "Street Level Geocode Reliability Description",
            "locality_level_longitude": "Locality Level Longitude",
            "locality_level_latitude": "Locality Level Latitude",
            "locality_level_planimetric_accuracy": "Locality Level Latitude",
            "locality_level_geocode_reliability_code": "Locality Level Geocode Reliability Code",
            "locality_level_geocode_reliability_description": "Locality Level Geocode Reliability Description",
            "gnaf_legal_parcel_identifier": "Gnaf Legal Parcel Identifier",
            "locality_class_code": "Locality Class Code"
        },
        aus_cv_household: {
            "address": "Address",
            "adults_at_address_code": "Adults At Address Code",
            "adults_at_address_description": "Adults At Address Description",
            "affluence_code": "Affluence Code",
            "affluence_description": "Affluence Description",
            "channel_preference": "Channel Preference",
            "channel_preference_description": "Channel Preference Description",
            "children_at_address_code_0_10_years": "Children At Address Code 0 10 Years",
            "children_at_address_code_11_18_years": "Children At Address Code 11 18 Years",
            "children_at_address_description_0_10_years": "Children At Address Description 0 10 Years",
            "children_at_address_description_11_18_years": "Children At Address Description 11 18 Years",
            "credit_demand_code": "Credit Demand Code",
            "credit_demand_description": "Credit Demand Description",
            "gnaf_latitude": "Gnaf Latitude",
            "gnaf_longitude": "Gnaf Longitude",
            "gnaf_pid": "Gnaf Pid",
            "head_of_household_age_code": "Head Of Household Age Code",
            "head_of_household_age_description": "Head Of Household Age Description",
            "hin": "Hin",
            "household_composition_code": "Household Composition Code",
            "household_composition_description": "Household Composition Description",
            "household_income_code": "Household Income Code",
            "household_income_description": "Household Income Description",
            "length_of_residence_code": "Length Of Residence Code",
            "length_of_residence_description": "Length Of Residence Description",
            "lifestage_code": "Lifestage Code",
            "lifestage_description": "Lifestage Description",
            "local_government_area_code": "Local Government Area Code",
            "local_government_area_name": "Local Government Area Name",
            "meshblock": "Meshblock",
            "mosaic_factor1_percentile": "Mosaic Factor1 Percentile",
            "mosaic_factor1_score": "Mosaic Factor1 Score",
            "mosaic_factor2_percentile": "Mosaic Factor2 Percentile",
            "mosaic_factor2_score": "Mosaic Factor2 Score",
            "mosaic_factor3_percentile": "Mosaic Factor3 Percentile",
            "mosaic_factor3_score": "Mosaic Factor3 Score",
            "mosaic_factor4_percentile": "Mosaic Factor4 Percentile",
            "mosaic_factor4_score": "Mosaic Factor4 Score",
            "mosaic_factor5_percentile": "Mosaic Factor5 Percentile",
            "mosaic_factor5_score": "Mosaic Factor5 Score",
            "mosaic_group": "Mosaic Group",
            "mosaic_segment": "Mosaic Segment",
            "mosaic_type": "Mosaic Type",
            "postcode": "Postcode",
            "residential_flag": "Residential Flag",
            "risk_insight_code": "Risk Insight Code",
            "risk_insight_description": "Risk Insight Description",
            "sa1": "Sa1",
            "state": "State",
            "suburb": "Suburb"
        }
    },
    NZL: {
        nzl_regional_geocodes: {
            "front_of_property_nztm_x_coordinate": "Front of Property NZTM X Coordinate",
            "front_of_property_nztm_y_coordinate": "Front of Property NZTM Y Coordinate",
            "centroid_of_property_nztm_x_coordinate": "Centroid of Property NZTM X Coordinate",
            "centroid_of_property_nztm_y_coordinate": "Centroid of Property NZTM Y Coordinate",
            "front_of_property_latitude": "Front of Property Latitude",
            "front_of_property_longitude": "Front of Property Longitude",
            "centroid_of_property_latitude": "Centroid of Property Latitude",
            "centroid_of_property_longitude": "Centroid of Property Longitude",
            "linz_parcel_id": "Linz Parcel Id",
            "property_purpose_type": "Property Purpose Type",
            "addressable": "Addressable",
            "mesh_block_code": "Mesh Block Code",
            "territorial_authority_code": "Territorial Authority Code",
            "territorial_authority_name": "Territorial Authority Name",
            "regional_council_code": "Regional Council Code",
            "regional_council_name": "Regional Council Name",
            "general_electorate_code": "General Electorate Code",
            "general_electorate_name": "General Electorate Name",
            "maori_electorate_code": "Maori Electorate Code",
            "maori_electorate_name": "Maori Electorate Name",
            "match_level": "Match Level"
        },
        nzl_cv_household: {
            "adults_at_address": "Adults At Address",
            "children_at_address": "Children At Address",
            "head_of_household_age": "Head Of Household Age",
            "head_of_household_lifestage": "Head Of Household Lifestage",
            "household_composition": "Household Composition",
            "mosaic_group": "Mosaic Group",
            "mosaic_segment": "Mosaic Segment",
            "mosaic_type_group": "Mosaic Type Group"
        }
    },
    USA: {
        usa_regional_geocodes: {
            "latitude": "Latitude",
            "longitude": "Longitude",
            "match_level": "Match Level",
            "census_tract": "Census Tract",
            "census_block": "Census Block",
            "core_based_statistical_area": "Core Based Statistical Area",
            "congressional_district_code": "Congressional District Code",
            "county_code": "Country Code"
        }
    },
    GBR: {
        uk_location_essential: {
            "latitude": "Latitude",
            "longitude": "Longitude",
            "match_level": "Match Level",
            "udprn": "UDPRN",
            "uprn": "UPRN",
            "x_coordinate": "X Coordinate",
            "y_coordinate": "Y Coordinate"
        },
        what3words: {
            "latitude": "Latitude",
            "longitude": "Longitude",
            "name": "Name",
            "description": "Description"
        }
    },
    GLOBAL: {
        geocodes: {
            "latitude": "Latitude",
            "longitude": "Longitude",
            "match_level": "Match Level"
        }
    }
};